# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9b82093b4d3153ce0efbba25bc2efaf1a00f8e20ae8520f2f21938d039d5e49b1f1a1f965c75c63ef15c566e10f45ef3132736c71702a744c617ed52d9dfa00

test:
  secret_key_base: 0f238d85f3360647455d46d7869731f885b929ebbe71aa6d6bae3616e719fbecbfec472017f1ea86b2123135810ff4c2d4bd17513445b709fab371a99cad5fb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 'efc7accf674a265876f59c4dfe3d1df36019018acbb8e0bdefec5f6b15464d953159d848b8c6ae665993aad93ebb8b8dfe5103488de31a9bcfa7bd5bfbd6c63c'

